language: java
jdk:
- oraclejdk8
before_script:
- psql -c 'create database eigenmusik;' -U postgres
install: mvn clean install -Dmaven.javadoc.skip=false -B -V -DskipTests=true
cache:
  directories:
  - .autoconf
  - $HOME/.m2
deploy:
  provider: heroku
  api_key:
    secure: K6wqQHyJIJ90jA7S5dHFgs85A5cXmxh8lsPU1upaxTqCp8IYyxQIdyXLCHbzEdOY4I21jiyRCn8Q8jLRVVAoZgoCc/RfFBBcl77xGQaOS/mdPFR8iYf/ATXXaheesBRn7OtMHLm/Qo3p8oCoSK/AJ48Ov8QUKUBbZsCJf6ykHuOGt90rcwmJtqsyTXUgthgKh4XLPmyTjGcOwVTCsWbuGmmInZRatKTmgGpc+2OAfY9ZnRYwhzTzui4p5dhJG7cCyA8xpdBg6v1rNGFv/xTLbj4TyH/DiTyyNUaWp/XaGqt6R2jwB9T7GTU+oval7oUN/Lfi7YC9QFOGlhLRSBfKDhsUQ8bKF1DtbTb55pJ+Yx/2vyeADLJnwESNiluC9jb/6RSq6WBYaRHbvkQa18DGMMLMUgF1UL3JWaHZyImDrE7Y5ObMU3DgM7Uwxb6as8GX+G4xsUKt3qLpSVflkskTy43en9N+VjhYBjDlN5HV/tO66i2hJHVeBXwAR7sOwQzU+svTie3vxzM7J/O6oBpmR4/J+SvJhZzrzsVnnkc7eFc/Y6TaQwxv0qFBnXywg9QONx5MFiiM4i+0fPw/8DM9R2BSn5+KU0lNZNu7z3Sv7W3RjaMMwxT52mSCzucjdJ2ZCx0Bnh4KaJw+ykNiGYNR/N6o1RHUxqAXLC7SMjLeUvg=
