language: java
jdk:
- oraclejdk8
before_script:
  - psql -c 'create database eigenmusik;' -U postgres
install: mvn clean install -Dmaven.javadoc.skip=false -B -V -DskipTests=true 
cache:
  directories:
  - .autoconf
  - $HOME/.m2
deploy:
  provider: heroku
  api_key:
    secure: "Cpe23pMkS+D01d5bUxGzP3B+Hgs8jojALDZEruL/9e0bcbA5AfvBn/FYAln9oimc/kl4nusVzjh0a3C8wAlThDD3PkWKa+fydQetFvPWhchHEwES4Z3F/PkIP+USSTbT2xkYsgxEOXigSJR9Ppmg4wbl7u/YkjUE0Y1rgytKXCudLjprbbud6n9ZiLBtxoImYLh3cK/vl190hbiOeQ8eXbSj4mciY0BHdvHR8fovK6XiJEnRhvM0qCc5xkFhdDsSJK9kX09oFe4b30OCifM6WYghmfztt3gE+feBkJ0knpsBwHNty/XgaywUS23SWr2FSXq8nAtg6XUUxW7BJYnUCDlfGGMnugxoYauVyR2lo/dHvn0q7FJCh45hNTeiyGlC1fwmWgXp/9Kxs/zBrG+mONAYnkwvtsmd0h95+3arxrAhq8T1jsBJrTop6qRA5gZMF5YYF6diIjBy6MCh3HakpHhXVebyegy4NK1h1qNLcO99mm2YPlIASWdRxu6bW3eBAAj8z6E/0Hv5r/r1ct62KDLxo7CfHH0S6oHa+W2TOO5hQvBPSBLm4p1XVbLTMWuMqvr65ji99EdgBmYQAc+06cPizrx0RfI4RoeJ/rPERuoLDlZ9v9IQMbc4xF+lOJi6zs6vrcA8oJbeex1sRYItTa1NF4K0ewZWdAIDUaH1DNE="
